version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: image-viewer-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai  # 可根据需要调整时区
      MYSQL_DATABASE: imageviewer
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./config/db-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network      
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --init-file=/docker-entrypoint-initdb.d/init.sql  # 添加这一行
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend service
  backend:
    build: .
    container_name: image-viewer-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: imageviewer
      DB_USER: root
      DB_PASSWORD: 123456

  # Frontend service
  frontend:
    build: ./client
    container_name: image-viewer-frontend
    restart: always
    # 这里端口保持一样，为了docker 里面的nginx能访问vue history模式
    ports:
      - "8080:8080"
    depends_on:
      - backend

networks:
  mysql_network:
    driver: bridge